export const Constants = {
    ROUTES:{
        WELCOME:'/',
        HOME:'/home',
        LOGIN:'/login',
        REGISTER:'/register',
        MOVIE_DETAIL:'/movie_detail',
        MY_MOVIE_LIST:'/my_movie_list',
        PUBLIC_MOVIE_LIST:'/public_movie_list',
        CREATE_LIST:'/create_list'
    },
    API_ROUTES:{
        REGISTER:'/register',
        LOGIN:'/login',
        GET_PUBLIC_MOVIE_LIST:'/get_all_public_movie_list',
        GET_MY_MOVIE_LIST:'/get_my_movie_list'
    },
    STATUS_CODES:{
        SUCCESS:200,
        SERVER_CRASH:500,
        NOT_FOUND:404
    },
}